In [1]:
%matplotlib inline
import matplotlib
import seaborn as sns
import pandas as pd
import missingno as msno
import numpy as np
sns.set(style="white")
matplotlib.rc('figure', figsize=[12, 5])

In [2]:
Ins_df = pd.read_csv("finalapi.csv")
Ins_df.head()

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,RETENTION_POLY_QTY,POLY_INFORCE_QTY,PREV_POLY_INFORCE_QTY,NB_WRTN_PREM_AMT,...,PL_BOUND_CT_ELINKS,PL_QUO_CT_ELINKS,PL_BOUND_CT_PLRANK,PL_QUO_CT_PLRANK,PL_BOUND_CT_eQTte,PL_QUO_CT_eQTte,PL_BOUND_CT_APPLIED,PL_QUO_CT_APPLIED,PL_BOUND_CT_TRANSACTNOW,PL_QUO_CT_TRANSACTNOW
0,3,3,BOILERMACH,CL,IN,2005,0,0,0,40.0,...,0,0,0,103,50,288,0,0,0,0
1,3,3,BOILERMACH,CL,IN,2006,0,0,0,151.0,...,0,0,0,103,50,288,0,0,0,0
2,3,3,BOILERMACH,CL,IN,2007,0,0,0,40.0,...,0,0,0,103,50,288,0,0,0,0
3,3,3,BOILERMACH,CL,IN,2008,0,0,0,69.0,...,0,0,0,103,50,288,0,0,0,0
4,3,3,BOILERMACH,CL,IN,2009,0,0,0,28.0,...,0,0,0,103,50,288,0,0,0,0

In [5]:
# We only work on 23 Columns so a data field on those columns

Updated_Ins_df = Ins_df[["AGENCY_ID","PRIMARY_AGENCY_ID","PROD_ABBR","PROD_LINE","STATE_ABBR",
                         "STAT_PROFILE_DATE_YEAR","NB_WRTN_PREM_AMT","WRTN_PREM_AMT",
                         "PREV_WRTN_PREM_AMT","PRD_ERND_PREM_AMT","PRD_INCRD_LOSSES_AMT",
                         "LOSS_RATIO_3YR","ACTIVE_PRODUCERS","MAX_AGE","MIN_AGE","VENDOR_IND","VENDOR",
                         "PL_START_YEAR","PL_END_YEAR","COMMISIONS_START_YEAR","COMMISIONS_END_YEAR",
                         "CL_START_YEAR","CL_END_YEAR"]]

Updated_Ins_df.head()

Updated_Ins_df.to_csv('output.csv', index=False)

In [9]:
# Locate value 9999 in Agency_ID

Updated_Ins_df.loc[Updated_Ins_df['AGENCY_ID'] == 99999]

# Looks like we ar good with Agency_ID

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [14]:
# Locate value 99999 in PRIMARY_AGENCY_ID

Updated_Ins_df.loc[Updated_Ins_df['PRIMARY_AGENCY_ID'] == 99999]

# THere are 37874  rows with value 99999 my proposal is to drop these columns

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
511,11,99999,BOILERMACH,CL,IN,2005,0.0,242.00,99999.00,134.61,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
512,11,99999,BOILERMACH,CL,IN,2006,0.0,406.00,406.00,406.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
513,11,99999,BOILERMACH,CL,IN,2007,0.0,406.00,406.00,405.61,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
514,11,99999,BOILERMACH,CL,IN,2008,0.0,164.00,406.00,381.86,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
515,11,99999,BOILERMACH,CL,IN,2009,0.0,70.31,164.00,1.87,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
516,11,99999,BOILERMACH,CL,IN,2010,0.0,0.00,70.31,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
517,11,99999,BOILERMACH,CL,IN,2011,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
518,11,99999,BOILERMACH,CL,IN,2012,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
519,11,99999,BOP,CL,IN,2005,0.0,4129.00,3258.58,2980.26,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
520,11,99999,BOP,CL,IN,2006,0.0,-1887.45,4729.00,1003.75,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
521,11,99999,BOP,CL,IN,2007,0.0,514.64,-1887.45,570.36,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
522,11,99999,BOP,CL,IN,2008,0.0,0.00,688.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
523,11,99999,COMMAUTO,CL,IN,2005,0.0,0.00,74.51,173.17,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
524,11,99999,COMMAUTO,CL,IN,2006,0.0,258.00,258.00,258.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
525,11,99999,COMMAUTO,CL,IN,2007,0.0,235.84,258.00,242.97,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
526,11,99999,COMMAUTO,CL,IN,2008,0.0,170.00,235.84,170.34,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
527,11,99999,COMMAUTO,CL,IN,2009,0.0,64.27,170.00,7.45,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
528,11,99999,COMMAUTO,CL,IN,2010,0.0,0.00,64.27,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
529,11,99999,COMMAUTO,CL,IN,2011,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
530,11,99999,COMMAUTO,CL,IN,2012,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
531,11,99999,COMMINLMAR,CL,IN,2005,0.0,0.00,0.00,218.82,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
532,11,99999,COMMINLMAR,CL,IN,2006,0.0,343.00,326.00,341.56,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
533,11,99999,COMMINLMAR,CL,IN,2007,0.0,264.80,343.00,293.93,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
534,11,99999,COMMINLMAR,CL,IN,2008,0.0,0.00,354.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
535,11,99999,COMMINLMAR,CL,WV,2013,0.0,0.00,99999.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
536,11,99999,COMMINLMAR,CL,WV,2014,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
537,11,99999,COMMINLMAR,CL,WV,2015,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
538,11,99999,COMMPOL,CL,IN,2005,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
539,11,99999,COMMPOL,CL,IN,2006,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
540,11,99999,COMMPOL,CL,IN,2007,0.0,0.00,0.00,0.00,...,87,36,N,Unknown,99999,99999,99999,99999,99999,99999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212523,9966,99999,HOMEOWNERS,PL,OH,2006,637.0,843.83,630.00,874.92,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212524,9966,99999,HOMEOWNERS,PL,OH,2007,0.0,762.00,843.83,746.35,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212525,9966,99999,HOMEOWNERS,PL,OH,2008,0.0,799.00,762.00,776.52,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212526,9966,99999,HOMEOWNERS,PL,OH,2009,0.0,752.00,799.00,780.24,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212527,9966,99999,HOMEOWNERS,PL,OH,2010,0.0,-431.77,752.00,-367.90,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212528,9966,99999,HOMEOWNERS,PL,OH,2011,0.0,0.00,-431.77,0.00,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212529,9966,99999,HOMEOWNERS,PL,OH,2012,0.0,0.00,0.00,0.00,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212530,9966,99999,PERSUMBREL,PL,KY,2005,0.0,0.00,0.00,112.26,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212531,9966,99999,PERSUMBREL,PL,KY,2006,0.0,167.25,167.25,167.25,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212532,9966,99999,PERSUMBREL,PL,KY,2007,0.0,172.83,167.25,171.42,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212533,9966,99999,PERSUMBREL,PL,KY,2008,0.0,172.83,172.83,173.21,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212534,9966,99999,PERSUMBREL,PL,KY,2009,0.0,217.43,172.83,209.25,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212535,9966,99999,PERSUMBREL,PL,KY,2010,0.0,0.00,217.43,35.14,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212536,9966,99999,PERSUMBREL,PL,KY,2011,0.0,0.00,0.00,0.00,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212537,9966,99999,PERSUMBREL,PL,KY,2012,0.0,0.00,0.00,0.00,...,76,31,N,Unknown,99999,99999,99999,99999,99999,99999
212971,9975,99999,GENERALIAB,CL,PA,2005,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212972,9975,99999,GENERALIAB,CL,PA,2006,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212973,9975,99999,GENERALIAB,CL,PA,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212974,9975,99999,GENERALIAB,CL,PA,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212975,9975,99999,ANNIV,PL,PA,2005,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212976,9975,99999,ANNIV,PL,PA,2006,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212977,9975,99999,ANNIV,PL,PA,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212978,9975,99999,ANNIV,PL,PA,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212979,9975,99999,ANNIV,PL,PA,2009,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212980,9975,99999,ANNIV,PL,PA,2010,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212981,9975,99999,ANNIV,PL,PA,2011,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212982,9975,99999,ANNIV,PL,PA,2012,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212983,9975,99999,ANNIV,PL,PA,2013,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212984,9975,99999,ANNIV,PL,PA,2014,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
212985,9975,99999,ANNIV,PL,PA,2015,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999

In [25]:
# creat a new df where  PRIMARY_AGENCY_ID =99999 is ignored

new_df = Updated_Ins_df[Updated_Ins_df["PRIMARY_AGENCY_ID"] != 99999]

In [22]:
# Locate value 99999 in PROD_ABBR

new_df.loc[new_df['PROD_ABBR'] == 99999]

# THere are no values so we should be good.

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [26]:
# Locate value 99999 in PROD_LINE

new_df.loc[new_df['PROD_LINE'] == 99999]

# THere are no values of 99999 so we should be good.

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [27]:
# Locate value 99999 in STATE_ABBR

new_df.loc[new_df['STATE_ABBR'] == 99999]

# THere are no values of 99999 so we should be good.

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [28]:
# Locate value 99999 in STAT_PROFILE_DATE_YEAR

new_df.loc[new_df['STAT_PROFILE_DATE_YEAR'] == 99999]

# THere are no values of 99999 so we should be good.

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [29]:
# Locate value 99999 in NB_WRTN_PREM_AMT

new_df.loc[new_df['NB_WRTN_PREM_AMT'] == 99999]

# THere is only 1 value with 99999

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
209024,9733,9733,FIREALLIED,CL,OH,2014,99999.0,267009.56,189909.87,240894.29,...,87,35,Y,C,2000,99999,2010,99999,2013,99999

In [30]:
# Locate value 99999 in NB_WRTN_PREM_AMT

new_df.loc[new_df['WRTN_PREM_AMT'] == 99999]

# THere is no value with 99999

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [31]:
# Locate value 99999 in PREV_WRTN_PREM_AMT

new_df.loc[new_df['PREV_WRTN_PREM_AMT'] == 99999]

# THere is 12000 rows value with 99999

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
66,3,3,COMMAUTO,CL,MI,2010,0.00,0.00,99999.0,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
72,3,3,COMMAUTO,CL,OH,2005,0.00,0.00,99999.0,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
76,3,3,COMMAUTO,CL,OH,2009,0.00,0.00,99999.0,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
91,3,3,COMMAUTO,CL,PA,2013,0.00,0.00,99999.0,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
94,3,3,COMMAUTO,CL,WV,2008,0.00,0.00,99999.0,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
247,3,3,GENERALIAB,CL,OH,2015,0.00,521.00,99999.0,521.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
270,3,3,WORKCOMP,CL,PA,2008,0.00,896.00,99999.0,896.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
311,3,3,ANNIV 12,PL,IN,2012,15932.00,15848.23,99999.0,6829.87,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
315,3,3,ANNIV 12,PL,KY,2012,7805.67,7805.67,99999.0,2546.85,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
368,3,3,DWELLFIRE,PL,KY,2009,1391.00,1464.00,99999.0,826.96,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
375,3,3,DWELLFIRE,PL,OH,2011,630.00,630.00,99999.0,82.62,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
424,3,3,MOTORHOM12,PL,IN,2012,292.50,292.50,99999.0,150.69,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
439,3,3,MOTORHOME,PL,KY,2005,0.00,98.52,99999.0,96.35,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
480,3,3,PERSUMBREL,PL,OH,2007,131.00,131.00,99999.0,67.29,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
665,16,16,BOILERMACH,CL,OH,2005,0.00,73.21,99999.0,133.43,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
751,16,16,CRIME,CL,OH,2008,2031.00,2182.00,99999.0,962.80,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
774,16,16,GARAGE,CL,OH,2008,27506.00,26985.00,99999.0,12198.70,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
793,16,16,GENERALIAB,CL,WV,2008,0.00,60.00,99999.0,35.18,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
809,16,16,ANNIV,PL,WV,2009,339.60,339.60,99999.0,282.39,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
816,16,16,ANNIV 12,PL,OH,2012,18159.25,14570.72,99999.0,7266.08,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
820,16,16,ANNIV 12,PL,WV,2012,2395.00,615.51,99999.0,615.51,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
843,16,16,DTALK 12,PL,OH,2013,419.30,419.30,99999.0,411.26,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
901,16,16,MOTORHOM12,PL,OH,2012,410.50,327.27,99999.0,179.92,...,74,29,Y,C,2003,99999,2011,99999,2011,99999
1291,46,46,COMMAUTO,CL,PA,2008,0.00,0.00,99999.0,0.00,...,70,27,Y,E,2012,99999,2009,99999,2012,99999
1384,46,46,ANNIV 12,PL,OH,2012,934.60,934.60,99999.0,442.98,...,70,27,Y,E,2012,99999,2009,99999,2012,99999
1451,46,46,PERSINLMAR,PL,OH,2005,157.00,157.00,99999.0,72.69,...,70,27,Y,E,2012,99999,2009,99999,2012,99999
1484,61,8365,BOILERMACH,CL,PA,2008,204.00,204.00,99999.0,128.74,...,69,32,Y,E,2008,99999,2008,99999,2011,99999
1492,61,8365,COMMAUTO,CL,PA,2008,9632.00,9576.79,99999.0,5702.26,...,69,32,Y,E,2008,99999,2008,99999,2011,99999
1500,61,8365,COMMINLMAR,CL,PA,2008,1418.00,1426.50,99999.0,841.33,...,69,32,Y,E,2008,99999,2008,99999,2011,99999
1508,61,8365,COMMPOL,CL,PA,2008,0.00,0.00,99999.0,0.00,...,69,32,Y,E,2008,99999,2008,99999,2011,99999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212366,9960,9960,PERSUMBREL,PL,OH,2012,145.00,145.00,99999.0,81.04,...,45,27,Y,A,2009,99999,2009,99999,2012,99999
212560,9969,8652,BOILERMACH,CL,OH,2011,28.00,28.00,99999.0,24.47,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212639,9969,8652,COMMINLMAR,CL,OH,2011,565.00,565.00,99999.0,493.79,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212640,9969,8652,COMMINLMAR,CL,OH,2012,0.00,0.00,99999.0,71.21,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212663,9969,8652,COMMPOL,CL,OH,2011,0.00,0.00,99999.0,0.00,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212734,9969,8652,FIREALLIED,CL,OH,2011,111.00,111.00,99999.0,97.02,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212783,9969,8652,GENERALIAB,CL,OH,2008,18.00,18.00,99999.0,6.66,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212791,9969,8652,GENERALIAB,CL,PA,2014,0.00,-325.00,99999.0,-325.00,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212819,9969,8652,WORKCOMP,CL,PA,2014,0.00,-42.00,99999.0,-42.00,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212832,9969,8652,ANNIV,PL,KY,2006,883.25,1696.20,99999.0,1218.27,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212835,9969,8652,ANNIV,PL,KY,2011,636.73,287.79,99999.0,287.79,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212840,9969,8652,ANNIV 12,PL,IN,2013,1445.30,3427.10,99999.0,3112.94,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212843,9969,8652,ANNIV 12,PL,KY,2013,3822.01,1691.72,99999.0,1691.71,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212846,9969,8652,CYCLES,PL,IN,2007,192.90,192.90,99999.0,93.81,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212910,9969,8652,MOBILEHOME,PL,IN,2009,401.00,401.00,99999.0,385.62,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212917,9969,8652,MOTORHOM12,PL,IN,2013,628.90,628.90,99999.0,575.49,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212931,9969,8652,PERSINLMAR,PL,IN,2005,0.00,115.67,99999.0,155.63,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212953,9969,8652,PERSUMBREL,PL,KY,2006,569.02,569.02,99999.0,402.21,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212960,9969,8652,YACHT,PL,IN,2005,407.00,407.00,99999.0,304.41,...,69,38,Y,E,2004,99999,2009,99999,99999,99999
212986,9998,9998,BOILERMACH,CL,IN,2005,52.00,152.00,99999.0,139.30,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213056,9998,9998,COMMAUTO,CL,OH,2005,2403.00,2403.00,99999.0,803.21,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213064,9998,9998,COMMINLMAR,CL,IN,2005,0.00,0.00,99999.0,34.91,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213072,9998,9998,COMMINLMAR,CL,IN,2015,133.00,133.00,99999.0,55.39,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213158,9998,9998,GARAGE,CL,KY,2009,0.00,11220.80,99999.0,8054.38,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213184,9998,9998,GENERALIAB,CL,OH,2005,798.35,0.00,99999.0,0.00,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213232,9998,9998,ANNIV 12,PL,IN,2012,4146.20,4146.20,99999.0,22.66,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213236,9998,9998,ANNIV 12,PL,KY,2012,19762.06,20522.57,99999.0,9759.58,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213263,9998,9998,DWELLFIRE,PL,KY,2010,628.00,628.00,99999.0,426.70,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213310,9998,9998,PERSINLMAR,PL,KY,2005,0.00,-288.72,99999.0,-8.61,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213325,9998,9998,PERSUMBREL,PL,KY,2013,132.19,132.19,99999.0,101.77,...,83,44,Y,C,2002,99999,99999,99999,2011,99999

In [37]:
# replace PREV_WRTN_PREM_AMT all values from 99999 to 0

new_df.loc[:, 'PREV_WRTN_PREM_AMT'].replace([99999], [0], inplace=True)
new_df.head()

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
0,3,3,BOILERMACH,CL,IN,2005,40.0,3074.63,149.00,3005.77,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
1,3,3,BOILERMACH,CL,IN,2006,151.0,6562.28,5438.55,6433.44,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
2,3,3,BOILERMACH,CL,IN,2007,40.0,6205.11,6562.28,6357.09,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
3,3,3,BOILERMACH,CL,IN,2008,69.0,5159.89,6205.11,5315.01,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
4,3,3,BOILERMACH,CL,IN,2009,28.0,4527.71,5159.89,4706.47,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999

In [34]:
# Locate value 99999 in PREV_WRTN_PREM_AMT

new_df.loc[new_df['PRD_ERND_PREM_AMT'] == 99999]

# THere is 12000 rows value with 99999

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [35]:
# Locate value 99999 in PREV_WRTN_PREM_AMT

new_df.loc[new_df['PRD_INCRD_LOSSES_AMT'] == 99999]

# THere is 12000 rows value with 99999

Empty DataFrame
Columns: [AGENCY_ID, PRIMARY_AGENCY_ID, PROD_ABBR, PROD_LINE, STATE_ABBR, STAT_PROFILE_DATE_YEAR, NB_WRTN_PREM_AMT, WRTN_PREM_AMT, PREV_WRTN_PREM_AMT, PRD_ERND_PREM_AMT, PRD_INCRD_LOSSES_AMT, LOSS_RATIO_3YR, ACTIVE_PRODUCERS, MAX_AGE, MIN_AGE, VENDOR_IND, VENDOR, PL_START_YEAR, PL_END_YEAR, COMMISIONS_START_YEAR, COMMISIONS_END_YEAR, CL_START_YEAR, CL_END_YEAR]
Index: []

[0 rows x 23 columns]

In [43]:
# Locate value 99999 in PREV_WRTN_PREM_AMT

new_df.loc[new_df['LOSS_RATIO_3YR'] == 99999]

# THere is 12000 rows value with 99999

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
0,3,3,BOILERMACH,CL,IN,2005,40.00,3074.63,149.00,3005.77,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
10,3,3,BOILERMACH,CL,IN,2015,0.00,1922.83,1453.42,1534.44,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
11,3,3,BOILERMACH,CL,KY,2005,0.00,361.68,46.54,216.20,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
21,3,3,BOILERMACH,CL,KY,2015,0.00,0.00,0.00,530.27,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
22,3,3,BOP,CL,IN,2005,0.00,13607.47,13588.09,17667.42,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
32,3,3,BOP,CL,IN,2015,0.00,16094.00,15460.00,9379.11,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
33,3,3,BOP,CL,KY,2005,0.00,1796.91,2129.48,2503.38,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
43,3,3,BOP,CL,KY,2015,0.00,375.42,375.42,1013.89,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
44,3,3,COMMAUTO,CL,IN,2005,49.00,101913.67,113084.20,287741.66,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
54,3,3,COMMAUTO,CL,IN,2015,0.00,65658.31,62079.95,47620.08,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
55,3,3,COMMAUTO,CL,KY,2005,0.00,10019.49,8682.98,6769.34,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
65,3,3,COMMAUTO,CL,KY,2015,0.00,-0.01,0.00,1779.87,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
71,3,3,COMMAUTO,CL,MI,2015,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
72,3,3,COMMAUTO,CL,OH,2005,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
82,3,3,COMMAUTO,CL,OH,2015,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
83,3,3,COMMAUTO,CL,PA,2005,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
93,3,3,COMMAUTO,CL,PA,2015,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
99,3,3,COMMINLMAR,CL,IN,2005,111.00,6850.32,5813.38,15088.71,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
109,3,3,COMMINLMAR,CL,IN,2015,0.00,3603.39,3085.30,2574.09,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
110,3,3,COMMINLMAR,CL,KY,2005,0.00,2615.62,2051.93,1775.63,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
120,3,3,COMMINLMAR,CL,KY,2015,0.00,0.00,0.00,125.99,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
121,3,3,COMMPOL,CL,IN,2005,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
131,3,3,COMMPOL,CL,IN,2015,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
132,3,3,COMMPOL,CL,KY,2005,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
142,3,3,COMMPOL,CL,KY,2015,0.00,0.00,0.00,0.00,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
143,3,3,COMMUMBREL,CL,IN,2005,0.00,4499.06,3268.79,9623.82,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
153,3,3,COMMUMBREL,CL,IN,2015,0.00,5492.00,2827.00,2831.40,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
154,3,3,COMMUMBREL,CL,KY,2005,0.00,2062.13,634.50,1389.82,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
164,3,3,COMMUMBREL,CL,KY,2015,0.00,0.00,0.00,1388.07,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
165,3,3,CRIME,CL,IN,2005,0.00,100.00,511.43,548.68,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213173,9998,9998,GENERALIAB,CL,KY,2005,10614.05,18705.61,10258.43,18353.29,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213183,9998,9998,GENERALIAB,CL,KY,2015,970.79,6986.96,8177.54,8494.51,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213184,9998,9998,GENERALIAB,CL,OH,2005,798.35,0.00,0.00,0.00,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213188,9998,9998,WORKCOMP,CL,IN,2005,0.00,2352.60,79.00,436.37,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213198,9998,9998,WORKCOMP,CL,IN,2015,0.00,0.00,0.00,0.00,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213199,9998,9998,WORKCOMP,CL,KY,2005,0.00,1288.72,1807.00,738.64,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213209,9998,9998,WORKCOMP,CL,KY,2015,0.00,563.00,589.00,296.85,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213210,9998,9998,ANNIV,PL,IN,2005,4532.64,16553.06,10198.28,16366.18,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213220,9998,9998,ANNIV,PL,IN,2015,170.49,10083.66,12626.97,11328.48,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213221,9998,9998,ANNIV,PL,KY,2005,493.15,16053.85,16572.76,17231.66,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213231,9998,9998,ANNIV,PL,KY,2015,0.00,5686.73,5727.82,5248.99,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213235,9998,9998,ANNIV 12,PL,IN,2015,0.00,5047.35,11778.25,4142.14,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213239,9998,9998,ANNIV 12,PL,KY,2015,8881.21,14377.53,5860.83,13609.27,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213240,9998,9998,DTALK,PL,IN,2005,1724.93,23949.22,29198.77,26091.65,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213248,9998,9998,DWELLFIRE,PL,IN,2005,471.00,248.21,494.32,1083.23,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213258,9998,9998,DWELLFIRE,PL,IN,2015,0.00,0.00,0.00,992.88,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213259,9998,9998,DWELLFIRE,PL,KY,2005,0.00,0.00,0.00,0.00,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213268,9998,9998,DWELLFIRE,PL,KY,2015,1096.00,2348.82,2677.00,2371.79,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213269,9998,9998,HOMEOWNERS,PL,IN,2005,6717.00,56313.84,52196.46,53742.68,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213279,9998,9998,HOMEOWNERS,PL,IN,2015,0.00,13501.88,16188.33,28433.18,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213280,9998,9998,HOMEOWNERS,PL,KY,2005,5131.00,26244.07,21828.11,24413.10,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213290,9998,9998,HOMEOWNERS,PL,KY,2015,1250.00,8127.26,10142.14,16756.60,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213291,9998,9998,MOBILEHOME,PL,KY,2005,0.00,0.00,-52.19,-0.01,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213295,9998,9998,MOTORHOME,PL,IN,2005,21.00,131.00,89.00,88.75,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213305,9998,9998,MOTORHOME,PL,IN,2015,0.00,0.00,0.00,0.00,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213306,9998,9998,PERSINLMAR,PL,IN,2005,0.00,0.00,-70.06,0.00,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213310,9998,9998,PERSINLMAR,PL,KY,2005,0.00,-288.72,0.00,-8.61,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213314,9998,9998,PERSUMBREL,PL,IN,2005,0.00,2609.00,3216.00,1938.34,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213324,9998,9998,PERSUMBREL,PL,IN,2015,0.00,185.00,215.00,882.39,...,83,44,Y,C,2002,99999,99999,99999,2011,99999
213327,9998,9998,PERSUMBREL,PL,KY,2015,0.00,158.63,132.19,59.46,...,83,44,Y,C,2002,99999,99999,99999,2011,99999

In [41]:
# Find out the median value of LOSS_RATIO_3YR 


new_df.LOSS_RATIO_3YR.median()

0.52323817

In [44]:
# replace the 

new_df.loc[:, 'LOSS_RATIO_3YR'].replace([99999], [new_df.LOSS_RATIO_3YR.median()], inplace=True)
new_df.head()

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
0,3,3,BOILERMACH,CL,IN,2005,40.0,3074.63,149.00,3005.77,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
1,3,3,BOILERMACH,CL,IN,2006,151.0,6562.28,5438.55,6433.44,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
2,3,3,BOILERMACH,CL,IN,2007,40.0,6205.11,6562.28,6357.09,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
3,3,3,BOILERMACH,CL,IN,2008,69.0,5159.89,6205.11,5315.01,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999
4,3,3,BOILERMACH,CL,IN,2009,28.0,4527.71,5159.89,4706.47,...,85,48,N,Unknown,99999,99999,99999,99999,99999,99999

In [46]:
# Locate value 99999 in PREV_WRTN_PREM_AMT

new_df.loc[new_df['ACTIVE_PRODUCERS'] == 99999]

# THere is 12000 rows value with 99999

,AGENCY_ID,PRIMARY_AGENCY_ID,PROD_ABBR,PROD_LINE,STATE_ABBR,STAT_PROFILE_DATE_YEAR,NB_WRTN_PREM_AMT,WRTN_PREM_AMT,PREV_WRTN_PREM_AMT,PRD_ERND_PREM_AMT,...,MAX_AGE,MIN_AGE,VENDOR_IND,VENDOR,PL_START_YEAR,PL_END_YEAR,COMMISIONS_START_YEAR,COMMISIONS_END_YEAR,CL_START_YEAR,CL_END_YEAR
5297,291,291,ANNIV,PL,OH,2005,0.0,4560.58,5928.96,5183.08,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5298,291,291,ANNIV,PL,OH,2006,0.0,5849.58,7561.78,6415.74,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5299,291,291,ANNIV,PL,OH,2007,0.0,4232.70,5849.58,4526.63,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5300,291,291,ANNIV,PL,OH,2008,0.0,3000.48,4232.70,3168.84,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5301,291,291,ANNIV,PL,OH,2009,0.0,950.20,3000.48,1549.99,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5302,291,291,ANNIV,PL,OH,2010,0.0,592.60,950.20,600.65,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5303,291,291,ANNIV,PL,OH,2011,0.0,172.61,592.60,378.12,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5304,291,291,ANNIV,PL,OH,2012,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5305,291,291,DTALK,PL,OH,2005,0.0,-166.97,309.00,148.86,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5306,291,291,DTALK,PL,OH,2006,0.0,0.00,142.03,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5307,291,291,DTALK,PL,OH,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5308,291,291,DTALK,PL,OH,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5309,291,291,HOMEOWNERS,PL,OH,2005,0.0,643.00,389.00,492.44,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5310,291,291,HOMEOWNERS,PL,OH,2006,0.0,763.00,980.00,760.86,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5311,291,291,HOMEOWNERS,PL,OH,2007,0.0,904.00,763.00,767.89,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5312,291,291,HOMEOWNERS,PL,OH,2008,0.0,440.00,904.00,787.28,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5313,291,291,HOMEOWNERS,PL,OH,2009,0.0,377.90,440.00,723.40,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5314,291,291,HOMEOWNERS,PL,OH,2010,0.0,0.00,377.90,-257.05,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5315,291,291,HOMEOWNERS,PL,OH,2011,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5316,291,291,HOMEOWNERS,PL,OH,2012,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5317,291,291,MOTORHOME,PL,OH,2005,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5318,291,291,MOTORHOME,PL,OH,2006,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5319,291,291,MOTORHOME,PL,OH,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5320,291,291,MOTORHOME,PL,OH,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5865,307,307,BOILERMACH,CL,PA,2012,0.0,721.94,0.00,1276.45,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5866,307,307,BOILERMACH,CL,PA,2013,0.0,0.00,721.94,228.33,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5867,307,307,BOILERMACH,CL,PA,2014,0.0,330.73,0.00,486.22,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5868,307,307,BOILERMACH,CL,PA,2015,0.0,0.00,0.00,122.05,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5869,307,307,BOP,CL,PA,2012,0.0,698.40,0.00,1229.72,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
5870,307,307,BOP,CL,PA,2013,0.0,0.00,698.40,31.25,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203632,9570,9570,DWELLFIRE,PL,OH,2008,0.0,109.00,108.00,108.17,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203633,9570,9570,DWELLFIRE,PL,OH,2009,0.0,110.00,109.00,109.12,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203634,9570,9570,DWELLFIRE,PL,OH,2010,0.0,-110.00,110.00,-14.16,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203635,9570,9570,DWELLFIRE,PL,OH,2011,0.0,0.00,-110.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203636,9570,9570,DWELLFIRE,PL,OH,2012,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203637,9570,9570,HOMEOWNERS,PL,OH,2005,0.0,1862.00,1550.06,1228.53,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203638,9570,9570,HOMEOWNERS,PL,OH,2006,0.0,2039.00,1862.00,1948.06,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203639,9570,9570,HOMEOWNERS,PL,OH,2007,0.0,2095.00,2039.00,2062.90,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203640,9570,9570,HOMEOWNERS,PL,OH,2008,0.0,2142.00,2095.00,2120.80,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203641,9570,9570,HOMEOWNERS,PL,OH,2009,0.0,1527.44,2142.00,1957.21,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203642,9570,9570,HOMEOWNERS,PL,OH,2010,0.0,1635.00,1527.44,1504.50,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203643,9570,9570,HOMEOWNERS,PL,OH,2011,0.0,8903.82,1635.00,18519.50,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203644,9570,9570,HOMEOWNERS,PL,OH,2012,0.0,-329.70,8903.82,999.89,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203645,9570,9570,HOMEOWNERS,PL,OH,2013,0.0,0.00,-329.70,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203646,9570,9570,HOMEOWNERS,PL,OH,2014,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203647,9570,9570,HOMEOWNERS,PL,OH,2015,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203648,9570,9570,MOBILEHOME,PL,OH,2005,0.0,-149.69,0.00,53.88,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203649,9570,9570,MOBILEHOME,PL,OH,2006,0.0,0.00,66.31,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203650,9570,9570,MOBILEHOME,PL,OH,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203651,9570,9570,MOBILEHOME,PL,OH,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203652,9570,9570,MOTORHOME,PL,OH,2005,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203653,9570,9570,MOTORHOME,PL,OH,2006,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203654,9570,9570,MOTORHOME,PL,OH,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203655,9570,9570,MOTORHOME,PL,OH,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203656,9570,9570,MOTORHOME,PL,OH,2011,0.0,-42.07,0.00,-42.07,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203657,9570,9570,MOTORHOME,PL,OH,2012,0.0,0.00,-42.07,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203658,9570,9570,PERSUMBREL,PL,OH,2005,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203659,9570,9570,PERSUMBREL,PL,OH,2006,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203660,9570,9570,PERSUMBREL,PL,OH,2007,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999
203661,9570,9570,PERSUMBREL,PL,OH,2008,0.0,0.00,0.00,0.00,...,99999,99999,N,Unknown,99999,99999,99999,99999,99999,99999